apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky-deployment
  labels:
    app: tasky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      containers:
      - name: tasky-container
        image: 536697230138.dkr.ecr.us-east-1.amazonaws.com/freddyscs/tasky:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "3000"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: tasky-secrets
              key: MONGODB_USER
        - name: MONGODB_PASS
          valueFrom:
            secretKeyRef:
              name: tasky-secrets
              key: MONGODB_PASS
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: tasky-secrets
              key: SECRET_KEY
