apiVersion: v1
kind: Pod
metadata:
  name: kubectl-test
spec:
  serviceAccountName: tasky-admin
  containers:
  - name: kubectl
    image: bitnami/kubectl:latest
    command: [ "sleep", "3600" ]
  restartPolicy: Never
