apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  username: ZnJlZGR5c2Nz          # base64 encoded "freddyscs"
  password: ZnJlZGR5c2NzUGFzcw==  # base64 encoded "freddyscsPass"
  secretkey: c2VjcmV0MTIz          # base64 encoded "secret123"